name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ocaml/opam2:4.08
    steps:
      - uses: actions/checkout@v2
      - name: Compile & Install
        run: eval $(opam env) && opam install .
      - name: Install (local)
        run: eval $(opam env) && dune build @install
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          # A directory to store and save the cache
          path: _install
          key: build
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: CI build
          # Directory containing files to upload
          path: _install
  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ocaml/opam2:4.08
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build docs
        run: |
          eval $(opam env)
          opam install . && opam install odoc
          dune build @doc

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          build_dir: _build/default/_doc/html
